### ISSUE TITLE
Volume not working

### ISSUE THREAD

**Issue by ProfiSkiller** [Twasi/websocket-obs-java#1]

**Comment by LarsBaertschi** [comment]
Hey ProfiSkiller,

thank you for raising this issue. I just checked, and I am able to change the volume when using the following Versions:
OBS Studio (64 bit): 23.1.0
OBS Websocket: 4.6.1

Code I used to test:

```java
controller.setVolume("Desktop Audio", 0.8, res -> {
  System.out.println("Volume of 'Desktop Audio' set to 0.01 (1%)");
});

controller.getVolume("Desktop Audio", res -> {
  System.out.println("Volume of 'Desktop Audio' set to " + ((GetVolumeResponse) res).getVolume());
});
```
Please note that the volume is not linear. This is due to the OBS Api.

Please also note that the number has to be between 0.0 and 1.0, you may not specify percent (80).

If this does not solve your problem, please provide better reproduction steps.

Best regards,
Lars
