### ISSUE TITLE
Refresh Cache

### ISSUE THREAD

**Issue by menkian** [Twasi/websocket-obs-java#10]
This is my first GitHub post,
There's a chance to add Browser souce refresh cache feature?

**Comment by LarsBaertschi** [comment]
Welcome to GitHub! 👯 

I'm not exactly certain how these things would behave, but I would recommend to call the setSourceSettings endpoint and change the "Source" property (as documented in the request here: https://github.com/Twasi/websocket-obs-java/blob/66ddee6573c681829f1e5ffcf39b455c85043284/src/test/java/net/twasi/obsremotejava/test/OBSRemoteControllerTest.java#L156) to a similar URL.

If you, as an example, have the website https://twasi.net open, then you could change the source to https://twasi.net#randomnumber (where you generate a random number, for example). This should trigger a reload, however it does not reset the cache.

I don't think there is any way to reset the cache, since that does not seem to be supported by the OBS-Websocket plugin: https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md

**Comment by DieserMerlin** [comment]
Hey, welcome to GitHub :)

This is currently not implemented in the Websocket plugin for OBS. Please consider to open an issue on the plugins GitHub page (https://github.com/Palakis/obs-websocket/) an then create a new issue here when it is implemented.

Meanwhile the fix @LarsBaertschi suggested should work fine.
