### ISSUE TITLE
Replace System.out / System.err with Logs

### ISSUE THREAD

**Issue by cluder** [Twasi/websocket-obs-java#7]
OBSCommunicator.java contains various System.out calls they should be replaced with logs, so we can enable / disable them easier.

**Comment by LarsBaertschi** [comment]
I agree, I will have a look and implement proper login soon!

**Comment by cluder** [comment]
you can check out my commit, for some ideas
https://github.com/cluder/websocket-obs-java/commit/029b51e09869c8ad8aa677ff202335c63db027e6

**Comment by TinaTiel** [comment]
Howdy! I've fixed this in my fork at 4bfd6ceee662226efd493d29812b0a0c5047a271 if you want to take a look and incorporate into this one. Would love to contribute!

**Comment by TinaTiel** [comment]
Holup, I forgot about the e.printStacktrace calls...

**Comment by TinaTiel** [comment]
Okay, that took longer than expected but should now be done. See https://github.com/TinaTiel/websocket-obs-java/issues/2

A few things of note:

- I've set some reasonable defaults for the logging levels, including disabling Jetty logging. 
- Default log level for the project is debug (see next points)
- Since this seems to be built around registering callbacks, what I've done is replaced direct error logging with calls to the respective runOnError, runOnConnectionFailed, etc. methods. 

Inside those runOn... methods, I set it to DEBUG log the intended message so that the client knows something happened. I also include a debug message stating that no callback was registered, if relevant, so that they can know to register their own callbacks if they need to react to those kinds of events.

**Comment by TinaTiel** [comment]
Should add that while digging into the Integration Tests I found I broke a few -- this has been fixed. I've also broken up the tests a little bit and added a few comments to make them a bit easier to (at this point, manually) run with OBS. 

See https://github.com/TinaTiel/websocket-obs-java/issues/6

**Comment by TinaTiel** [comment]
@LarsBaertschi I have a branch ready for you for a PR, but I don't have permission to push branches to your remote.

**Comment by TinaTiel** [comment]
Noice! Thanks 👍
